name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if that's your default branch

permissions:
  contents: write  # needed to push to the repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # root folder where index.html is
